### ISSUE TITLE
Exposed MySQL Password

### ISSUE THREAD

**Issue by jaredhowland** [kenirwin/Weeding-Helper#15]
Your demo site is currently displaying an error message that also exposes your MySQL password. You may want to change that ASAP and suppress error messages.

**Comment by kenirwin** [comment]
@jaredhowland -- thanks for alerting me to this. Can you point to the page with the error? (I'm looking at https://www6.wittenberg.edu/lib/iii/weed/demo/ -- I see the error where it looks like a config file is displaying, but I don't see a password in it.)

**Comment by kenirwin** [comment]
@jaredhowland - nevermind, I see it now.

**Comment by kenirwin** [comment]
That problem has been resolved. 

Were you looking at using Weeding Helper? It looks like there may no longer be a viable demo, but if you'd like to have a look at it I may be able to set something up. 

Thanks!

**Comment by jaredhowland** [comment]
I was looking at it but mostly because I have used the LcSort class a couple of times and was checking to see if it had been updated since I last used it 8 or so years ago. No need to put up a demo—thanks though!
